# Generated by Django 4.0.2 on 2022-02-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customerreviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerreviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
